/** 一覧シートと同じ役割列（members JSON のキー） */
export const MEMBER_ROLE_KEYS = [
  "Vo.",
  "Vo. & Glo. & 鍵ハ.",
  "Vo. & Glo.",
  "Vo. & 鍵ハ.",
  "Vo. & Rap.",
  "Rap.",
  "Cho.",
  "Cho. & Tamb.",
  "Cho. & Sleighbells. & 鍵ハ.",
  "Vo. & Cho.",
  "Vo. & Tamb.",
  "Vo. & Sleighbells.",
  "Cho. & Sleighbells.",
  "Gt. & Vo.",
  "Gt.",
  "Gt. & Cho.",
  "Gt. & Rap.",
  "Ba.",
  "Ba. & Vo.",
  "Ba. & Cho.",
  "Ba. & Cj.",
  "Dr.",
  "Dr. & Vo.",
  "Dr. & Cho.",
  "Cj.",
  "Cj. & Vo.",
  "Cj. & Cho.",
  "Cj. & Perc.",
  "Pf.",
  "Pf. & Vo.",
  "Pf. & Cho.",
  "Pf. & Rap.",
  "Key. & Vo.",
  "Key. & Cho.",
  "Key.",
  "鍵ハ.",
  "鍵ハ. & Glo.",
  "ASax.",
  "TSax.",
  "BSax.",
  "SSax.",
  "Tp.",
  "Tb.",
  "Fl.",
  "Cl.",
  "Hr.",
  "Ob.",
  "Cym.",
  "Snare.",
  "Perc.",
  "Sleighbells.",
  "Glo.",
  "Bongo.",
  "Eu.",
  "Vn.",
  "Tamb.",
  "Shaker.",
  "Sleighbells. & Tamb. & 指揮者.",
  "指揮者.",
  "マイクスタンド.",
  "ミカルゲ.",
  "Block.",
  "影.",
  "浮雲.",
  "Other",
  "Other 2",
  "Other 3",
  "Other 4",
  "Other 5",
  "Other 6",
  "Vo.(Gt.&Vo.)",
  "Gt. 2",
] as const;

export type MemberRoleKey = (typeof MEMBER_ROLE_KEYS)[number];
